name: Mobile

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: popeen/Booksonic-App
          submodules: "recursive"
          path: booksonic

      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"

      - run: wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.1.0/uber-apk-signer-1.1.0.jar -O uber-apk-signer.jar

      - run: chmod +x booksonic/gradlew
      - run: ./gradlew assembleRelease
        working-directory: booksonic

      - run: java -jar uber-apk-signer.jar --ks release-key.keystore --ksAlias alias_name --ksPass ${{ secrets.KS_PASS }} --ksKeyPass ${{ secrets.KS_PASS }} --apks booksonic/app/build/outputs/apk/floss/release/*.apk -o signed

      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: signed
